PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX auth: <https://ekgf.org/ontology/authorization#>
PREFIX user-account: <https://ekgf.org/ontology/user-account/>

SELECT DISTINCT
    ?graph
    ?persona
    ?authorizationRule
    ?userGroup
    ?userGroupLabel
WHERE {
    GRAPH ?graph {
        ?authorizationRule a auth:AuthorizationRule ;
            auth:hasPersona ?persona ;
            auth:hasGroup ?userGroup .
        OPTIONAL {
            GRAPH ?userGroupGraph {
                ?userGroup a user-account:UserGroup ;
                    rdfs:label ?userGroupLabel .
            }
        }
    }
}
ORDER BY ?authorizationRule
?userGroup
