name: Setup cargo-edit
description: Install cargo-edit (provides cargo set-version) with caching

runs:
  using: composite
  steps:
    - name: Setup cargo-binstall
      uses: ./.github/actions/setup-cargo-binstall

    - name: Ensure cargo bin directory exists
      shell: bash
      run: mkdir -p "$HOME/.cargo/bin"

    - name: Cache cargo-edit binary
      uses: actions/cache@v4
      id: cache-cargo-edit
      with:
        path: ~/.cargo/bin/cargo-set-version${{ runner.os == 'Windows' && '.exe' || '' }}
        key: cargo-edit-0.13.0-${{ runner.os }}-${{ runner.arch }}

    - name: Install cargo-edit if not cached
      if: steps.cache-cargo-edit.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Installing cargo-edit via cargo-binstall..."
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo binstall --no-confirm --force --version 0.13.0 cargo-edit
        echo "✓ cargo-edit installed"

    - name: Verify installation
      shell: bash
      run: |
        CARGO_SET_VERSION_BIN="$HOME/.cargo/bin/cargo-set-version${{ runner.os == 'Windows' && '.exe' || '' }}"
        if [ -f "$CARGO_SET_VERSION_BIN" ]; then
          chmod +x "$CARGO_SET_VERSION_BIN"
          "$CARGO_SET_VERSION_BIN" --version
        else
          echo "❌ Error: cargo-set-version binary not found at $CARGO_SET_VERSION_BIN"
          echo "Checking cargo bin directory:"
          ls -la "$HOME/.cargo/bin/" || echo "Directory does not exist"
          exit 1
        fi
