name: Setup cargo-fmt-toml
description: Install cargo-fmt-toml with caching for Cargo.toml formatting

runs:
  using: composite
  steps:
    - name: Setup cargo-binstall
      uses: ./.github/actions/setup-cargo-binstall

    - name: Ensure cargo bin directory exists
      shell: bash
      run: mkdir -p "$HOME/.cargo/bin"

    - name: Add cargo bin to PATH
      shell: bash
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cache cargo-fmt-toml binary
      uses: actions/cache@v4
      id: cache-cargo-fmt-toml
      with:
        path: ~/.cargo/bin/cargo-fmt-toml${{ runner.os == 'Windows' && '.exe' || '' }}
        key: cargo-fmt-toml-latest-${{ runner.os }}-${{ runner.arch }}

    - name: Install cargo-fmt-toml if not cached
      if: steps.cache-cargo-fmt-toml.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "Installing cargo-fmt-toml via cargo-binstall..."
        CARGO_FMT_TOML_BIN="$HOME/.cargo/bin/cargo-fmt-toml"${{ runner.os == 'Windows' && '.exe' || '' }}

        # Check if binary already exists (from previous run or cache)
        if [ -f "$CARGO_FMT_TOML_BIN" ]; then
          echo "✓ cargo-fmt-toml binary already exists at $CARGO_FMT_TOML_BIN"
          chmod +x "$CARGO_FMT_TOML_BIN"
        else
          # Binary doesn't exist, install it
          echo "Binary not found, installing cargo-fmt-toml..."
          cargo binstall --no-confirm cargo-fmt-toml

          # Verify binary exists and make it executable
          if [ -f "$CARGO_FMT_TOML_BIN" ]; then
            chmod +x "$CARGO_FMT_TOML_BIN"
            echo "✓ cargo-fmt-toml installed and made executable"
          else
            echo "❌ Error: Binary not found at $CARGO_FMT_TOML_BIN after installation"
            echo "Checking cargo bin directory:"
            ls -la "$HOME/.cargo/bin/" || echo "Directory does not exist"
            echo "Checking if cargo-fmt-toml is in PATH:"
            which cargo-fmt-toml || echo "cargo-fmt-toml not in PATH"
            exit 1
          fi
        fi

    - name: Ensure cached binary is executable or install
      if: steps.cache-cargo-fmt-toml.outputs.cache-hit == 'true'
      shell: bash
      run: |
        CARGO_FMT_TOML_BIN="$HOME/.cargo/bin/cargo-fmt-toml"${{ runner.os == 'Windows' && '.exe' || '' }}
        if [ -f "$CARGO_FMT_TOML_BIN" ]; then
          chmod +x "$CARGO_FMT_TOML_BIN"
          echo "✓ Ensured cached cargo-fmt-toml binary is executable"
        else
          echo "⚠ Cached binary not found at $CARGO_FMT_TOML_BIN, installing..."
          cargo binstall --no-confirm cargo-fmt-toml

          # Verify binary exists and make it executable
          if [ -f "$CARGO_FMT_TOML_BIN" ]; then
            chmod +x "$CARGO_FMT_TOML_BIN"
            echo "✓ cargo-fmt-toml installed and made executable"
          else
            echo "❌ Error: Binary not found at $CARGO_FMT_TOML_BIN after installation"
            echo "Checking cargo bin directory:"
            ls -la "$HOME/.cargo/bin/" || echo "Directory does not exist"
            echo "Checking if cargo-fmt-toml is in PATH:"
            which cargo-fmt-toml || echo "cargo-fmt-toml not in PATH"
            exit 1
          fi
        fi

    - name: Verify installation
      shell: bash
      run: |
        CARGO_FMT_TOML_BIN="$HOME/.cargo/bin/cargo-fmt-toml"${{ runner.os == 'Windows' && '.exe' || '' }}
        if [ -f "$CARGO_FMT_TOML_BIN" ]; then
          "$CARGO_FMT_TOML_BIN" --version || cargo fmt-toml --version
        else
          echo "Error: cargo-fmt-toml binary not found at $CARGO_FMT_TOML_BIN"
          echo "Checking PATH: $PATH"
          echo "Checking cargo bin directory:"
          ls -la "$HOME/.cargo/bin/" || echo "Directory does not exist"
          exit 1
        fi
