name: Generate Changelog
description: Generate changelog from conventional commits using cocogitto

inputs:
  release-tag:
    description: "Release tag (e.g., v0.0.1)"
    required: true
  output-file:
    description: "File to write changelog to"
    required: false
    default: "CHANGELOG.md"

runs:
  using: composite
  steps:
    - name: Setup Cocogitto
      uses: ./.github/actions/setup-cocogitto

    - name: Generate changelog
      shell: bash
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cog changelog --at "${{ inputs.release-tag }}" > "${{ inputs.output-file }}"
        echo "Generated changelog at ${{ inputs.output-file }}"
